//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.04 at 12:55:01 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gb.com/hiring-exercise", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.gb.hiring_exercise;
