//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.04 at 12:55:01 AM CEST 
//


package com.gb.hiring_exercise;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vatRate" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="vatAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="netAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="grossAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vat", propOrder = {
    "vatRate",
    "vatAmount",
    "netAmount",
    "grossAmount"
})
public class Vat {

    protected int vatRate;
    protected double vatAmount;
    protected double netAmount;
    protected double grossAmount;

    /**
     * Gets the value of the vatRate property.
     * 
     */
    public int getVatRate() {
        return vatRate;
    }

    /**
     * Sets the value of the vatRate property.
     * 
     */
    public void setVatRate(int value) {
        this.vatRate = value;
    }

    /**
     * Gets the value of the vatAmount property.
     * 
     */
    public double getVatAmount() {
        return vatAmount;
    }

    /**
     * Sets the value of the vatAmount property.
     * 
     */
    public void setVatAmount(double value) {
        this.vatAmount = value;
    }

    /**
     * Gets the value of the netAmount property.
     * 
     */
    public double getNetAmount() {
        return netAmount;
    }

    /**
     * Sets the value of the netAmount property.
     * 
     */
    public void setNetAmount(double value) {
        this.netAmount = value;
    }

    /**
     * Gets the value of the grossAmount property.
     * 
     */
    public double getGrossAmount() {
        return grossAmount;
    }

    /**
     * Sets the value of the grossAmount property.
     * 
     */
    public void setGrossAmount(double value) {
        this.grossAmount = value;
    }

}
